import type { Metadata } from 'next'
import { Josefin_Sans,Jost } from 'next/font/google'
import {ChakraUIProvider} from "@/app/ChakraUIProvider";

const josefinSans = Josefin_Sans({ subsets: ['latin'] })
const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${josefinSans.className} ${jost.className}`}>
        <ChakraUIProvider>
          {children}
        </ChakraUIProvider>
      </body>
    </html>
  )
}
